services:
#    sitetranslate.example:
#        class: site\translateBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # fonctionnalit√©s de traduction
    aetools.translate:
        class: site\translateBundle\services\aeTranslate
        arguments: [@request, @aetools.aeSystemfiles, %default_locales%, %list_locales%, %locale%]
        scope: request
