imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: twigpages_globals.yml }
    - { resource: labo_parameters.yml }
    - { resource: labo_icons.yml }
    - { resource: cropper.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale:                 "fr"
    default_locales:        "fr|en"
    keywords:
        title: site.title
        description: site.description
        keywords: site.keywords
    formatDate:      "dd-MM-yyyy"
    formatDateHeure: "d-m-Y H:i:s"
    admin:
        accueil_nb_messages: 6


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        webmaster: %webmaster%
        sidemenuswitcher: true
        searchswitcher: false
        homepage: %homepage%
        formatDate: %formatDate%
        formatDateHeure: %formatDateHeure%
        formatDateOnly: %formatDateOnly%
        formFormatDate:  %formFormatDate%
        default_locales: %default_locales%
        list_locales: %list_locales%
        info_entites: %info_entites%
        marketplace: %marketplace%
        ajaxlive: %ajaxlive%
        serializer: %serializer%
        site_domains: %site_domains%
        site_titles: %site_titles%
    form:
        resources:
            # - 'sitegraphicsBundle:Form:form_div_layout.html.twig'
            # - 'sitegraphicsBundle:Form:form_table_layout.html.twig'
            # - 'sitegraphicsBundle:Form:bootstrap_3_horizontal_layout.html.twig'
            # - 'sitegraphicsBundle:Form:bootstrap_3_layout.html.twig'
            # - 'sitegraphicsBundle:Form:performed_bootstrap_3_horizontal_layout.html.twig'
            # - 'sitegraphicsBundle:Form:performed_bootstrap_3_layout.html.twig'
            - 'sitegraphicsBundle:Form:performed_bootstrap_3_horizontal_layout_laboadmin.html.twig'

braincrafted_bootstrap:
    auto_configure:
        assetic: false
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - LaboAdminBundle
        - siteadminsiteBundle
        - sitesiteBundle
        - siteUserBundle
        - FOSUserBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: ".less.css$"
            # Les deux lignes dci-dessous permettent de minifier le CSS compilé
            formatter: "compressed"
            preserve_comments: false
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor/build/yuicompressor-2.4.8.jar"
            timeout: 1200
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor/build/yuicompressor-2.4.8.jar"
            timeout: 1200
    assets:
        appleTouchIcon_png:
            inputs: ['%kernel.root_dir%/../app/Resources/favicons/apple-touch-icon.png']
            output: apple-touch-icon.png
        favicon_ico:
            inputs: ['%kernel.root_dir%/../app/Resources/favicons/favicon.ico']
            output: favicon.ico
        favicon_png:
            inputs: ['%kernel.root_dir%/../app/Resources/favicons/favicon.png']
            output: favicon.png
        favicon_16x16_ICO:
            inputs: ['%kernel.root_dir%/../app/Resources/favicons/favicon_16x16.ICO']
            output: favicon_16x16.ico
        favicon_72x72_ICO:
            inputs: ['%kernel.root_dir%/../app/Resources/favicons/favicon_72x72.ICO']
            output: favicon_72x72.ico
        favicon_114x114_ICO:
            inputs: ['%kernel.root_dir%/../app/Resources/favicons/favicon_114x114.ICO']
            output: favicon_114x114.ico
        favicon_144x144_ICO:
            inputs: ['%kernel.root_dir%/../app/Resources/favicons/favicon_144x144.ICO']
            output: favicon_144x144.ico
        favicon_144x144_PNG:
            inputs: ['%kernel.root_dir%/../app/Resources/favicons/favicon_144x144.PNG']
            output: favicon_144x144.png
        imago_css:
            inputs: ['bundles/sitesite/css/skins/imago.less.css']
            output: css/less/imago.css
            filters:
                - cssrewrite
                - lessphp
                - yui_css
        bootstrap_css:
            inputs:
                - bundles/sitesite/less/variables.less
                # - %kernel.root_dir%/../vendor/twbs/bootstrap/less/variables.less
                - %kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less
            filters:
                - lessphp
                - cssrewrite
            output: ~
        bootstrap_js:
            # filters: ['yui_js']
            inputs:
                # - %kernel.root_dir%/../vendor/twbs/bootstrap/js/*.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
            output: ~
        jquery_ui_css:
            filters:
                - lessphp
                - cssrewrite
            inputs:
                # - 'https://code.jquery.com/ui/1.12.1/themes/ui-darkness/jquery-ui.css'
                - 'bundles/sitesite/css/jquery-ui.css'
            output: ~
        jquery_js:
            # filters: ['yui_js']
            inputs:
                # - 'https://code.jquery.com/jquery-3.1.1.js'
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.12.0.js
            output: ~
        allJquery_js:
            # filters: ['yui_js']
            inputs:
                - @jquery_js
                # - 'https://code.jquery.com/ui/1.12.1/jquery-ui.js'
                - 'bundles/sitesite/js/jquery-ui.min.js'
            output: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            # gedmo_translatable:
            #     type: annotation
            #     prefix: Gedmo\Translatable\Entity
            #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            #     alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
            # gedmo_translator:
            #     type: annotation
            #     prefix: Gedmo\Translator\Entity
            #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
            #     alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
            # gedmo_loggable:
            #     type: annotation
            #     prefix: Gedmo\Loggable\Entity
            #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            #     alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
            # gedmo_tree:
            #     type: annotation
            #     prefix: Gedmo\Tree\Entity
            #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
            #     alias: GedmoTree # this one is optional and will default to the name set for the mapping 
            # gedmo_sortable:
            #     type: annotation
            #     prefix: Gedmo\Sortable\Entity
            #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Sortable/Entity"
            #     alias: GedmoSortable # this one is optional and will default to the name set for the mapping 

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUser Configuration
fos_user:
    db_driver:          orm  # le type de BDD à utiliser : ORM Doctrine
    firewall_name:      main # le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:         site\UserBundle\Entity\User # la classe de l'entité User que nous utilisons
    registration:
        form:
            type:       site_user_registration
        confirmation:
            enabled:    false # change to true for required email confirmation
            # template:   siteUserBundle:Registration:email.txt.twig
    profile:
        form:
            type: site_user_profile
    model_manager_name:       ~
    use_listener:             true
    use_flash_notifications:  true
    use_username_form_type:   true
    from_email: %mail%

# JMS Serializer configuration
jms_serializer:
  metadata:
    auto_detection: true
    debug: "%kernel.debug%"

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            tree: false
            sortable: true
            sluggable: true
            loggable: false
            timestampable: false
            translatable: false
